### ISSUE TITLE
Add scalariformTest task

### ISSUE THREAD

**Issue by lunaryorn** [sbt/sbt-scalariform#35] opened 2016-02-22 12:30 UTC
Similar to `scalariform --test`, this task would just check whether the code is properly formatted or not.  We'd like to use this for precommit hooks, and our Git server to ensure that only properly formatted source code gets pushed.

**Comment by fommil** [comment] 2016-02-22 13:07
dupe of #18 ?

**Comment by lunaryorn** [comment] 2016-02-22 13:13
I don't know.  I would prefer a separate task, and I don't think that it fits into `test` semantically.  And it doesn't make sense there: Since sbt-scalariform auto-formats by default, and test runs `compile`, there's no point in testing formatting as part of `sbt test`—code has been reformatted before in any case.

Ultimately the point of this is to have `sbt scalariformTest` in a pre-receive hook on our git server and reject all pushes that are not formatted properly.  We wouldn't want to run all unit tests on our git server, though.

**Comment by fommil** [comment] 2016-02-22 13:15
yeah, sounds like #18 would depend on this task.

FYI, this is how we do it now in `ensime-server` (requires a compile)

```
      sbt ++$SCALA_VERSION clean test:compile it:compile doc ;
      if [ $(git diff | wc -l) -ge 1 ] ; then
        echo "Code formatting does not meet the project's standards:" ;
        git --no-pager diff ;
        exit 1 ;
      fi
```

**Comment by lunaryorn** [comment] 2016-02-22 13:33
That wouldn't work in a pre-commit hook because you can't change git's index at this point.

Furthermore, with sbt-scalariform auto-formatting code on compile, testing formatting in `test` seems kind of pointless:  `test` depends on `compile`, so by the time formatting is to be checked all code has already been reformatted.

And scalariform's API is simple enough for this purpose:  It's as simple as replacing `File.write` in `Scalariform.scala` with `sys.err` to bail out if there's a different between the original contents and the formatted code.

**Comment by fommil** [comment] 2016-02-22 14:09
yeah, it is also annoying that we have to do the compile (which is CPU costly)

**Comment by lunaryorn** [comment] 2016-02-26 10:41
FWIW, that's the plugin I wrote for this purpose in our project:

```scala
import sbt._
import sbt.Keys._
import sbt.plugins.JvmPlugin
import scala.util.Try
import scalariform.formatter.ScalaFormatter
import scalariform.formatter.preferences.IFormattingPreferences
import com.typesafe.sbt.SbtScalariform.autoImport._
import scalariform.parser.ScalaParserException
import scala.language.postfixOps

sealed trait Error
case object InvalidSyntaxError extends Error
case object InvalidFormattingError extends Error

object ScalariformCheck extends AutoPlugin {
  object autoImport {
    val scalariformCheck = taskKey[Unit]("Check Scala formatting")
  }

  import autoImport._

  override val trigger = AllRequirements
  override val requires = JvmPlugin

  override val projectSettings = Seq(
    scalariformCheck := {
      val logger = streams.value.log
      val preferences = scalariformPreferences.value
      val directories = (sourceDirectories in Compile).value ++
        // Tests and integration tests are optional; we need to guard against these being undefined
        ((sourceDirectories in Test)?).value.getOrElse(Seq.empty) ++
        ((sourceDirectories in IntegrationTest)?).value.getOrElse(Seq.empty)
      val files = directories.descendantsExcept(
        (includeFilter in scalariformFormat).value,
        (excludeFilter in scalariformFormat).value
      )
      val misformattedFiles = files.get.count { file =>
        val source = IO.read(file)
        val error: Option[Error] = try {
          Option(source == ScalaFormatter.format(source, preferences, scalaVersion = scalaVersion.value))
            .collect{ case false => InvalidFormattingError }
        } catch {
          case e: ScalaParserException => Some(InvalidSyntaxError)
        }

        // Print a verbose error message for any failed files
        error.foreach {
          case InvalidSyntaxError => logger.error(s"${file} has invalid syntax")
          case InvalidFormattingError => logger.error(s"${file} is not formatted correctly")
        }
        error.isDefined
      }

      if (misformattedFiles > 0) {
        sys.error(s"${misformattedFiles} files misformatted")
      }
    }
  )
}
```

**Closed** 2020-05-07 11:59 UTC
