### ISSUE TITLE
Is this project superceded by daniel-trinh project?

### ISSUE THREAD

**Issue by ms-ati** [sbt/sbt-scalariform#29] opened 2015-12-31 04:42 UTC
Hi all,

Is this project superceded by https://github.com/daniel-trinh/sbt-scalariform ?

If so, would you mind explaining that in the README, so that people don't think scalariform is dead?

**Comment by eed3si9n** [comment] 2015-12-31 04:49
The plan is to let Daniel become the maintainer of this one. See https://github.com/sbt/sbt-scalariform/pull/28.

**Comment by ms-ati** [comment] 2015-12-31 05:27
Ah! Ok, thanks Eugene.

**Comment by fommil** [comment] 2016-01-12 19:58
dupe of #20

**Comment by fommil** [comment] 2016-01-12 20:34
watch this space :smile:

**Closed by fommil** 2016-01-12 20:34 UTC
